config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :clubs
  resources :locations
  resources :statuses

  root 'static_pages#home'
end

app/models/club.rb
class Club < ActiveRecord::Base
  belongs_to :location

  validates :name, presence: true, uniqueness: {case_sensitive: false}

end

app/models/club_status.rb
class ClubStatus < ActiveRecord::Base
  belongs_to :club
  belongs_to :status
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :clubs

  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :club_statuses
  has_many :clubs, through: :club_statuses

  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    clubs_path
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clubs_controller.rb
class ClubsController  < ApplicationController 
  before_action :find_club, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @clubs = Club.all
  end
  
  def show
  end
  
  def new
    @club = Club.new 
  end
  
  def create
    @club = Club.new(club_params)
    
    if @club.save
      flash[:notice] = 'Club was saved successfully'
      redirect_to clubs_path
    else
      flash.now[:error] = 'There was a problem saving this Club'
      render :new
    end
  end
  
  def edit   
  end
  
  def update
    if @club.update(club_params)
      redirect_to club_path(@club), notice: 'Club was updated successfully'    
    else
      flash.now[:error] = "There was an issue updating this Club"
      render :edit
    end
  end
  
  def destroy  
    @club.delete

    redirect_to clubs_path
  end

  private
  
  def find_club
    @club = Club.find_by_id(params[:id])
  end

  def club_params
    params.require(:club).permit(:name, :nickname, :manager, :rank, :location_id, :status_ids => [])
  end

end

app/controllers/locations_controller.rb
class LocationsController  < ApplicationController 
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @locations = Location.all
  end
  
  def show
    @location = Location.find_by_id(params[:id])
  end
  
  def new
    @location = Location.new 
  end
  
  def create
    @location = Location.new(location_params)
    
    if @location.save
      flash[:notice] = 'Location was saved successfully'
      redirect_to locations_path
    else
      flash.now[:error] = 'There was a problem saving this Location'
      render :new
    end
  end
  
  def edit 
    @location = Location.find_by_id(params[:id])  
  end
  
  def update
    @location = Location.find_by_id(params[:id])

    if @location.update(location_params)
      redirect_to locations_path, notice: 'Location was updated successfully'    
    else
      flash.now[:error] = "There was an issue updating this Location"
      render :edit
    end
  end
  
  def destroy 
    @location = Location.find_by_id(params[:id]) 

    @location.delete

    redirect_to locations_path
  end

  private
  
  def location_params
    params.require(:location).permit(:name)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    clubs_path # Or :prefix_to_your_route
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController  < ApplicationController
  def home
  end 
end

app/controllers/statuses_controller.rb
class StatusesController  < ApplicationController 
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @statuses = Status.all
  end
  
  def show
    @status = Status.find_by_id(params[:id])
  end
  
  def new
    @status = Status.new 
  end
  
  def create
    @status = Status.new(status_params)
    
    if @status.save
      flash[:notice] = 'Status was saved successfully'
      redirect_to statuses_path
    else
      flash.now[:error] = 'There was a problem saving this Status'
      render :new
    end
  end
  
  def edit 
    @status = Status.find_by_id(params[:id])  
  end
  
  def update
    @status = Status.find_by_id(params[:id])

    if @status.update(status_params)
      redirect_to statuses_path, notice: 'Status was updated successfully'    
    else
      flash.now[:error] = "There was an issue updating this Status"
      render :edit
    end
  end
  
  def destroy 
    @status = Status.find_by_id(params[:id]) 

    @status.delete

    redirect_to statuses_path
  end

  private
  
  def status_params
    params.require(:status).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clubs/_form.html.erb
<%= form_for @club do |f| %>

  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <b><%= f.label :name %></b>
    <%= f.text_field :name %>
  </p>
  <p>
    <b><%= f.label :nickname %></b>
    <%= f.text_field :nickname %>
  </p>
  <p>
    <b><%= f.label :manager %></b>
    <%= f.text_field :manager %>
  </p>
  <p>
    <b><%= f.label :rank %></b>
    <%= f.text_field :rank %>
  </p>
  <p>
    <b><%= f.label :location %></b>
    <%= collection_select(:club, :location_id, Location.all, :id, :name, {include_blank: true}) %>
  </p>
  <p>
    <b><%= f.label :status %></b> <br>
    <%= collection_check_boxes(:club, :status_ids, Status.all, :id, :name) %>
  </p>
  <p>
  <%= f.submit %>
  </p>

<% end %>

app/views/clubs/edit.html.erb
<h1>Edit Club</h1>

<h4 style="bottom: 0px; position: fixed;">  <%= link_to 'Home', clubs_path %></h4>

<%= render 'form' %>

app/views/clubs/index.html.erb
<h1>English Premier League</h1>
<h2>2015 - 2016</h2>

<% if current_user %>
  <h4><%= link_to 'Create New Club', new_club_path %></h4>
<% end %>
  
<h4><%= link_to 'Locations', locations_path %></h4>
<h4><%= link_to 'Statuses', statuses_path %></h4>


<table>
  <tr>
    <th>Name</th>
    
    <% if current_user %>
      <th></th>
    <% end %>

  </tr>
  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td style="padding-right: 20px; font-size: 20px"><%= link_to club.name, club_path(club) %></td>
        
        <% if current_user %>
          <td><%= link_to 'edit', edit_club_path(club) %></td> 
          <td><%= link_to 'delete', club_path(club), method: :delete, data: {confirm: "Are you sure you want to delete this club?"} %></td>
        <% end %>

      </tr>
    <% end %>          
  </tbody>
</table>

app/views/clubs/new.html.erb
<h1>Add Club</h1>

<h4 style="bottom: 0px; position: fixed;">  <%= link_to 'Home', clubs_path %></h4>

<%= render 'form' %>

app/views/clubs/show.html.erb
<% if @club %>

  <h1><%= @club.name %></h1>

  <p><b>Nickname: </b> <i><%= @club.nickname %></i></p>
  <p><b>Manager: </b> <i><%= @club.manager %></i></p>
  <p><b>Premier League Rank: </b> <i><%= @club.rank %></i></p>
  <p><b>Location: </b> <i><%= @club.location.try(:name) %></i></p>

  <p><b>Statuses: </b></p>
  <ul>
    <% @club.statuses.each do |status| %>
    <li><i><%= status.name %></i></li>
    <% end %>
  </ul>
  
<% else %>

  <h1> Club not found </h1>

<% end %>

<% if current_user %>
  <%= link_to 'edit', edit_club_path(@club) %> 
  <br>
  <%= link_to 'delete', club_path(@club), method: :delete, data: {confirm: "Are you sure you want to delete this club?"} %> 
<% end %>

<h4 style="bottom: 0px; position: fixed;">  <%= link_to 'Home', clubs_path %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EplApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if current_user %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", new_user_session_path%> |
      <%= link_to "Register", new_user_registration_path %>
    <% end %>

    <% flash.each do |name, msg| %>
      <div class="<%= name %>">
        <%= msg %>  
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>

  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <b><%= f.label :name %></b>
    <%= f.text_field :name %>
  </p>
  
  <p>
  <%= f.submit %>
  </p>

<% end %>

app/views/locations/edit.html.erb
<h1>Edit Location</h1>

<h4 style="bottom: 30px; position: fixed;">  <%= link_to 'Return to Locations', locations_path %></h4>

<h4 style="bottom: 0px; position: fixed;">  <%= link_to 'Home', clubs_path %></h4>

<%= render 'form' %>

app/views/locations/index.html.erb
<h1>English Premier League</h1>
<h2>2015 - 2016</h2>

<% if current_user %>
  <h4><%= link_to 'Create New Location', new_location_path %></h4>
<% end %>

<table>
  <tr>
    <th>Name</th>
    
    <% if current_user %>
      <th></th>
    <% end %>

  </tr>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td style="color: white; background-color: blue; padding-right: 20px; font-size: 20px"><%= location.name %></td>
        
        <% if current_user %>
          <td><%= link_to 'edit', edit_location_path(location) %></td> 
          <td><%= link_to 'delete', location_path(location), method: :delete, data: {confirm: "Are you sure you 
            want to delete this location?"} %></td>
        <% end %>

      </tr>
    <% end %>          
  </tbody>
</table>

<h4 style="bottom: 0px"> <%= link_to 'Home', clubs_path %></h4>

app/views/locations/new.html.erb
<h1>Add Location</h1>

<h4 style="bottom: 30px; position: fixed;">  <%= link_to 'Return to Locations', locations_path %></h4>

<h4 style="bottom: 0px; position: fixed;">  <%= link_to 'Home', clubs_path %></h4>

<%= render 'form' %>

app/views/static_pages/home.html.erb
<h1>Please Log in / Register</h1>

<h3><%= link_to 'Teaser', clubs_path %></h3>

app/views/statuses/_form.html.erb
<%= form_for @status do |f| %>

  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <b><%= f.label :name %></b>
    <%= f.text_field :name %>
  </p>
  
  <p>
  <%= f.submit %>
  </p>

<% end %>

app/views/statuses/edit.html.erb
<h1>Edit Status</h1>

<h4 style="bottom: 30px; position: fixed;">  <%= link_to 'Return to Statuses', statuses_path %></h4>

<h4 style="bottom: 0px; position: fixed;">  <%= link_to 'Home', clubs_path %></h4>

<%= render 'form' %>

app/views/statuses/index.html.erb
<h1>English Premier League</h1>
<h2>2015 - 2016</h2>

<% if current_user %>
  <h4><%= link_to 'Create New Status', new_status_path %></h4>
<% end %>

<table>
  <tr>
    <th>Name</th>
    
    <% if current_user %>
      <th></th>
    <% end %>
  
  </tr>
  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td style="color: white; background-color: blue; padding-right: 20px; font-size: 20px"><%= status.name %></td>
        
        <% if current_user %>
          <td><%= link_to 'edit', edit_status_path(status) %></td> 
          <td><%= link_to 'delete', status_path(status), method: :delete, data: {confirm: "Are you sure you want to delete this status?"} %></td>
        <% end %>

      </tr>
    <% end %>          
  </tbody>
</table>

<h4 style="bottom: 0px; position: fixed;"> <%= link_to 'Home', clubs_path %></h4>

app/views/statuses/new.html.erb
<h1>Add Status</h1>

<h4 style="bottom: 30px; position: fixed;">  <%= link_to 'Return to Statuses', statuses_path %></h4>

<h4 style="bottom: 0px; position: fixed;">  <%= link_to 'Home', clubs_path %></h4>

<%= render 'form' %>